version: "3"
services:
  mysql:
    container_name: samp-front-db
    image: mysql
    restart: always
    env_file:
      - ./../env/.env
    ports:
      - "3306:3306"
  app:
    image: eoussama/samp-front:0.5.1
    container_name: samp-front-app
    restart: always
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:80"
    # volumes:
    #   - ./../:/var/www/
    depends_on:
      - mysql
